apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-d
  labels: 
    app: app-d
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-d
  template:
    metadata:
      labels:
        app: app-d
    spec:
      containers:
        - image: giovanacosta/app-d:{{tag}}
          name: app-d
          ports:
            - containerPort: 80
              name: app-d